"use client";
import { useEffect, useState } from "react";
import { getEfrisConfig, getFiscalDocuments, getTaxRates, getTaxConfigurations, updateEfrisConfig, type EfrisConfig, type FiscalDocument, type TaxRate, type TaxConfiguration } from "../../lib/api";
export default function CompliancePage(){
 const [config,setConfig]=useState<EfrisConfig|null>(null); const [docs,setDocs]=useState<FiscalDocument[]>([]); const [taxRates,setTaxRates]=useState<TaxRate[]>([]); const [taxConfigs,setTaxConfigs]=useState<TaxConfiguration[]>([]); const [busy,setBusy]=useState(true); const [message,setMessage]=useState("");
 async function load(){setBusy(true);try{const [c,d,r,tc]=await Promise.all([getEfrisConfig(),getFiscalDocuments(),getTaxRates(),getTaxConfigurations()]);setConfig(c);setDocs(d);setTaxRates(r);setTaxConfigs(tc);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load compliance.")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function save(){if(!config)return;setMessage("");try{setConfig(await updateEfrisConfig({enabled:config.enabled,integration_mode:config.integration_mode,registration_status:config.registration_status,tin:config.tin,legal_name:config.legal_name,effective_date:config.effective_date}));setMessage("EFRIS configuration saved.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.")}}
 return <main className="workspace" style={{maxWidth:1500}}>
  <div className="workspace-header"><div><span className="workspace-breadcrumb">LEXA · COMPLIANCE</span><h1>Tax & EFRIS</h1><p>Compliance records are separate from internal payments and accounting truth.</p></div><div className="header-actions"><a className="button button-soft" href="/">Back</a><button className="button button-soft" onClick={load}>Refresh</button></div></div>
  {message&&<div className="inline-message">{message}</div>}
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">EFRIS CONFIGURATION</span><h2>Fiscalization readiness</h2></div></div>{config&&<div className="command-form"><label>Enabled<select value={config.enabled?"true":"false"} onChange={e=>setConfig({...config,enabled:e.target.value==="true"})}><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label>Integration mode<select value={config.integration_mode} onChange={e=>setConfig({...config,integration_mode:e.target.value})}><option>MANUAL</option><option>PENDING_INTEGRATION</option><option>SYSTEM_TO_SYSTEM</option></select></label><label>Registration status<select value={config.registration_status} onChange={e=>setConfig({...config,registration_status:e.target.value})}><option>NOT_REGISTERED</option><option>PENDING</option><option>ACTIVE</option><option>SUSPENDED</option></select></label><label>TIN<input value={config.tin||""} onChange={e=>setConfig({...config,tin:e.target.value||null})}/></label><label>Legal name<input value={config.legal_name||""} onChange={e=>setConfig({...config,legal_name:e.target.value||null})}/></label><button className="primary" onClick={save} disabled={busy}>Save configuration</button></div>}</section>
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">TAX CONFIGURATION</span><h2>{taxRates.length} rates · {taxConfigs.length} assignments</h2></div></div><div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Rate</th><th>Inclusive</th><th>Effective</th></tr></thead><tbody>{taxRates.map(t=><tr key={t.id}><td>{t.code}</td><td>{t.name}</td><td>{t.rate_percent}%</td><td>{t.inclusive?"Yes":"No"}</td><td>{t.effective_from}{t.effective_to?` → ${t.effective_to}`:""}</td></tr>)}</tbody></table></div><p style={{color:"#77849a",fontSize:11,marginTop:12}}>Tax rates are effective-dated and resolved deterministically. Historical sales retain their calculated tax amounts.</p></section>
<section className="workspace-section"><div className="section-head"><div><span className="section-label">FISCAL DOCUMENTS</span><h2>{docs.length} documents</h2></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Status</th><th>FDN</th><th>Verification</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.issue_date}</td><td>{d.document_type}</td><td>{d.status}</td><td>{d.fdn||"Not issued"}</td><td>{d.verification_code||"Not issued"}</td></tr>)}</tbody></table></div><p style={{color:"#77849a",fontSize:11,marginTop:12}}>LEXA records EFRIS results only after URA returns them. It never invents an FDN, verification code or QR code.</p></section>
 </main>
}
