-- LEXA 2.8.0 release convergence. Additive and idempotent.
-- Ensures the live purchasing/supplier contract, readiness contract and analytics semantics remain reproducible.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name varchar NOT NULL, code varchar NOT NULL, email varchar, phone varchar, currency char(3) NOT NULL DEFAULT 'UGX', status varchar NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT suppliers_status_check CHECK(status IN('ACTIVE','INACTIVE','ARCHIVED')), CONSTRAINT suppliers_currency_check CHECK(currency ~ '^[A-Z]{3}$'), UNIQUE(tenant_id,id));
CREATE UNIQUE INDEX IF NOT EXISTS uq_suppliers_tenant_code ON suppliers(tenant_id,code) WHERE status<>'ARCHIVED';
CREATE INDEX IF NOT EXISTS idx_suppliers_tenant_name ON suppliers(tenant_id,name,id) WHERE status<>'ARCHIVED';

CREATE TABLE IF NOT EXISTS supplier_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, supplier_party_id uuid NOT NULL, currency_code varchar NOT NULL DEFAULT 'UGX', payment_terms_days integer NOT NULL DEFAULT 0, default_receiving_location_id uuid, tax_number varchar, notes text, status varchar NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT supplier_profile_party_fk FOREIGN KEY(tenant_id,supplier_party_id) REFERENCES parties(tenant_id,id) ON DELETE CASCADE, CONSTRAINT supplier_profile_location_fk FOREIGN KEY(tenant_id,default_receiving_location_id) REFERENCES locations(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT supplier_profile_status_check CHECK(status IN('ACTIVE','INACTIVE','ARCHIVED')), CONSTRAINT supplier_profile_terms_check CHECK(payment_terms_days>=0), UNIQUE(tenant_id,supplier_party_id));

CREATE TABLE IF NOT EXISTS supplier_product_prices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, supplier_id uuid NOT NULL, variant_id uuid NOT NULL, supplier_sku varchar, unit_id uuid NOT NULL REFERENCES units(id) DEFERRABLE, unit_cost numeric NOT NULL, minimum_quantity numeric NOT NULL DEFAULT 1, lead_time_days integer, currency char(3) NOT NULL DEFAULT 'UGX', effective_from timestamptz NOT NULL, effective_to timestamptz, status varchar NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT fk_supplier_product_price_supplier_tenant FOREIGN KEY(tenant_id,supplier_id) REFERENCES suppliers(tenant_id,id) DEFERRABLE, CONSTRAINT fk_supplier_product_price_variant_tenant FOREIGN KEY(tenant_id,variant_id) REFERENCES product_variants(tenant_id,id) DEFERRABLE, CONSTRAINT supplier_product_prices_cost_check CHECK(unit_cost>=0), CONSTRAINT supplier_product_prices_min_qty_check CHECK(minimum_quantity>0), CONSTRAINT supplier_product_prices_interval_check CHECK(effective_to IS NULL OR effective_to>effective_from), CONSTRAINT supplier_product_prices_currency_check CHECK(currency ~ '^[A-Z]{3}$'), CONSTRAINT supplier_product_prices_status_check CHECK(status IN('ACTIVE','INACTIVE','ARCHIVED')), UNIQUE(tenant_id,id));
CREATE INDEX IF NOT EXISTS idx_supplier_product_prices_lookup ON supplier_product_prices(tenant_id,supplier_id,variant_id,unit_id,minimum_quantity,effective_from DESC);
CREATE INDEX IF NOT EXISTS supplier_product_prices_no_overlap ON supplier_product_prices USING gist(tenant_id,supplier_id,variant_id,unit_id,minimum_quantity,currency,tstzrange(effective_from,effective_to,'[)'));

CREATE TABLE IF NOT EXISTS supplier_variant_costs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, supplier_party_id uuid NOT NULL, variant_id uuid NOT NULL, currency_code varchar NOT NULL DEFAULT 'UGX', unit_cost numeric NOT NULL, minimum_quantity numeric NOT NULL DEFAULT 1, effective_from timestamptz NOT NULL DEFAULT now(), effective_to timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT svc_supplier_fk FOREIGN KEY(tenant_id,supplier_party_id) REFERENCES parties(tenant_id,id) ON DELETE CASCADE, CONSTRAINT svc_variant_fk FOREIGN KEY(tenant_id,variant_id) REFERENCES product_variants(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT svc_cost_check CHECK(unit_cost>0), CONSTRAINT svc_minimum_check CHECK(minimum_quantity>0), UNIQUE(tenant_id,supplier_party_id,variant_id,effective_from));
CREATE INDEX IF NOT EXISTS idx_supplier_costs_tenant_variant ON supplier_variant_costs(tenant_id,variant_id,effective_from DESC);

CREATE TABLE IF NOT EXISTS purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, po_number varchar NOT NULL, supplier_party_id uuid NOT NULL, branch_id uuid NOT NULL, receiving_location_id uuid NOT NULL, status varchar NOT NULL DEFAULT 'DRAFT', order_date date NOT NULL DEFAULT CURRENT_DATE, expected_date date, currency_code varchar NOT NULL DEFAULT 'UGX', notes text, subtotal numeric NOT NULL DEFAULT 0, tax_amount numeric NOT NULL DEFAULT 0, total numeric NOT NULL DEFAULT 0, created_by uuid, submitted_by uuid, approved_by uuid, cancelled_by uuid, closed_by uuid, created_at timestamptz NOT NULL DEFAULT now(), submitted_at timestamptz, approved_at timestamptz, cancelled_at timestamptz, closed_at timestamptz, CONSTRAINT po_supplier_fk FOREIGN KEY(tenant_id,supplier_party_id) REFERENCES parties(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT po_branch_fk FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT po_location_fk FOREIGN KEY(tenant_id,receiving_location_id) REFERENCES locations(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT po_status_check CHECK(status IN('DRAFT','SUBMITTED','OPEN','PARTIALLY_RECEIVED','FULLY_RECEIVED','CLOSED','CANCELLED')), CONSTRAINT po_amounts_check CHECK(subtotal>=0 AND tax_amount>=0 AND total>=0 AND total=subtotal+tax_amount), CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_orders_submitted_by_fkey FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_orders_approved_by_fkey FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_orders_cancelled_by_fkey FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_orders_closed_by_fkey FOREIGN KEY(closed_by) REFERENCES users(id) ON DELETE SET NULL, UNIQUE(tenant_id,po_number), UNIQUE(tenant_id,id));
CREATE INDEX IF NOT EXISTS idx_purchase_orders_tenant_status ON purchase_orders(tenant_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier ON purchase_orders(tenant_id,supplier_party_id,created_at DESC);

CREATE TABLE IF NOT EXISTS purchase_order_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, purchase_order_id uuid NOT NULL, line_number integer NOT NULL, variant_id uuid NOT NULL, ordered_quantity numeric NOT NULL, received_quantity numeric NOT NULL DEFAULT 0, unit_cost numeric NOT NULL, tax_rate numeric NOT NULL DEFAULT 0, tax_amount numeric NOT NULL DEFAULT 0, line_subtotal numeric NOT NULL DEFAULT 0, line_total numeric NOT NULL DEFAULT 0, description varchar, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT pol_po_fk FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES purchase_orders(tenant_id,id) ON DELETE CASCADE, CONSTRAINT pol_variant_fk FOREIGN KEY(tenant_id,variant_id) REFERENCES product_variants(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT pol_quantity_check CHECK(ordered_quantity>0 AND received_quantity>=0 AND received_quantity<=ordered_quantity), CONSTRAINT pol_amount_check CHECK(unit_cost>0 AND tax_rate>=0 AND tax_rate<=100 AND tax_amount>=0 AND line_subtotal>=0 AND line_total=line_subtotal+tax_amount), UNIQUE(tenant_id,id), UNIQUE(tenant_id,purchase_order_id,line_number), UNIQUE(tenant_id,purchase_order_id,variant_id));
CREATE INDEX IF NOT EXISTS idx_purchase_order_lines_po ON purchase_order_lines(tenant_id,purchase_order_id,line_number);

CREATE TABLE IF NOT EXISTS purchase_order_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, purchase_order_id uuid NOT NULL, from_status varchar, to_status varchar NOT NULL, actor_user_id uuid, reason text, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT posh_po_fk FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES purchase_orders(tenant_id,id) ON DELETE CASCADE, CONSTRAINT purchase_order_status_history_actor_user_id_fkey FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS purchase_receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, receipt_number varchar NOT NULL, purchase_order_id uuid NOT NULL, receiving_location_id uuid NOT NULL, status varchar NOT NULL DEFAULT 'DRAFT', received_at timestamptz NOT NULL DEFAULT now(), notes text, created_by uuid, posted_by uuid, created_at timestamptz NOT NULL DEFAULT now(), posted_at timestamptz, CONSTRAINT pr_po_fk FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES purchase_orders(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT pr_location_fk FOREIGN KEY(tenant_id,receiving_location_id) REFERENCES locations(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT pr_status_check CHECK(status IN('DRAFT','POSTED','CANCELLED')), CONSTRAINT purchase_receipts_created_by_fkey FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_receipts_posted_by_fkey FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL, UNIQUE(tenant_id,receipt_number), UNIQUE(tenant_id,id));
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_po ON purchase_receipts(tenant_id,purchase_order_id,created_at DESC);

CREATE TABLE IF NOT EXISTS purchase_receipt_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, receipt_id uuid NOT NULL, purchase_order_line_id uuid NOT NULL, variant_id uuid NOT NULL, received_quantity numeric NOT NULL, unit_cost numeric NOT NULL, variance_reason varchar, notes varchar, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT prl_receipt_fk FOREIGN KEY(tenant_id,receipt_id) REFERENCES purchase_receipts(tenant_id,id) ON DELETE CASCADE, CONSTRAINT prl_po_line_fk FOREIGN KEY(tenant_id,purchase_order_line_id) REFERENCES purchase_order_lines(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT prl_variant_fk FOREIGN KEY(tenant_id,variant_id) REFERENCES product_variants(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT prl_quantity_check CHECK(received_quantity>0 AND unit_cost>0), UNIQUE(tenant_id,id), UNIQUE(tenant_id,receipt_id,purchase_order_line_id));

CREATE TABLE IF NOT EXISTS purchase_returns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, return_number varchar NOT NULL, purchase_receipt_id uuid NOT NULL, receiving_location_id uuid NOT NULL, status varchar NOT NULL DEFAULT 'REQUESTED', reason varchar NOT NULL, notes text, created_by uuid, approved_by uuid, posted_by uuid, created_at timestamptz NOT NULL DEFAULT now(), approved_at timestamptz, posted_at timestamptz, CONSTRAINT pur_receipt_fk FOREIGN KEY(tenant_id,purchase_receipt_id) REFERENCES purchase_receipts(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT pur_location_fk FOREIGN KEY(tenant_id,receiving_location_id) REFERENCES locations(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT pur_status_check CHECK(status IN('REQUESTED','APPROVED','POSTED','CANCELLED')), CONSTRAINT purchase_returns_created_by_fkey FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_returns_approved_by_fkey FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT purchase_returns_posted_by_fkey FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL, UNIQUE(tenant_id,return_number), UNIQUE(tenant_id,id));
CREATE INDEX IF NOT EXISTS idx_purchase_returns_receipt ON purchase_returns(tenant_id,purchase_receipt_id,created_at DESC);

CREATE TABLE IF NOT EXISTS purchase_return_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, purchase_return_id uuid NOT NULL, purchase_receipt_line_id uuid NOT NULL, variant_id uuid NOT NULL, quantity numeric NOT NULL, unit_cost numeric NOT NULL, reason varchar, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT purl_return_fk FOREIGN KEY(tenant_id,purchase_return_id) REFERENCES purchase_returns(tenant_id,id) ON DELETE CASCADE, CONSTRAINT purl_receipt_line_fk FOREIGN KEY(tenant_id,purchase_receipt_line_id) REFERENCES purchase_receipt_lines(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT purl_variant_fk FOREIGN KEY(tenant_id,variant_id) REFERENCES product_variants(tenant_id,id) ON DELETE RESTRICT, CONSTRAINT purl_quantity_check CHECK(quantity>0 AND unit_cost>0), UNIQUE(tenant_id,id), UNIQUE(tenant_id,purchase_return_id,purchase_receipt_line_id));

DO $do$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['suppliers','supplier_profiles','supplier_product_prices','supplier_variant_costs','purchase_orders','purchase_order_lines','purchase_order_status_history','purchase_receipts','purchase_receipt_lines','purchase_returns','purchase_return_lines']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
    EXECUTE format('DROP POLICY IF EXISTS %I_tenant_isolation ON %I',t,t);
    EXECUTE format(
      'CREATE POLICY %I_tenant_isolation ON %I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)',
      t, t
    );
  END LOOP;
END $do$;

GRANT SELECT,INSERT,UPDATE,DELETE ON suppliers,supplier_profiles,supplier_product_prices,supplier_variant_costs,purchase_orders,purchase_order_lines,purchase_order_status_history,purchase_receipts,purchase_receipt_lines,purchase_returns,purchase_return_lines TO lexa_app;

INSERT INTO permissions(code,description) VALUES ('purchasing.read','View suppliers and purchasing state'),('purchasing.manage','Create and manage supplier and purchasing records'),('purchasing.approve','Approve purchase orders and purchasing returns'),('purchasing.receive','Receive purchase orders into inventory'),('purchasing.returns.manage','Manage purchase returns') ON CONFLICT(code) DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'purchasing.%' WHERE r.name IN('Owner','Administrator','Manager') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN('purchasing.read','purchasing.receive') WHERE r.name='Inventory' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code='purchasing.read' WHERE r.name IN('Finance / Accounting','Read-only') ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.lexa_business_date(p_at timestamptz,p_tenant_id uuid) RETURNS date LANGUAGE sql STABLE AS $$ SELECT (p_at AT TIME ZONE COALESCE((SELECT timezone FROM tenant_settings WHERE tenant_id=p_tenant_id),'UTC'))::date $$;

DO $do$ DECLARE def text; BEGIN SELECT pg_get_functiondef(p.oid) INTO def FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='refresh_analytics' AND p.pronargs=3 LIMIT 1; IF def IS NULL THEN RAISE EXCEPTION 'refresh_analytics function is missing'; END IF; def := replace(def,$$COALESCE(completed_at,created_at)::date$$,$$public.lexa_business_date(COALESCE(completed_at,created_at),p_tenant_id)$$); def := replace(def,$$COALESCE(s.completed_at,s.created_at)::date$$,$$public.lexa_business_date(COALESCE(s.completed_at,s.created_at),p_tenant_id)$$); def := replace(def,$$COALESCE(sr.completed_at,sr.created_at)::date$$,$$public.lexa_business_date(COALESCE(sr.completed_at,sr.created_at),p_tenant_id)$$); def := replace(def,$$current_date$$,$$public.lexa_business_date(now(),p_tenant_id)$$); def := replace(def,$$COALESCE(-SUM(CASE WHEN it.quantity_delta<0 THEN it.quantity_delta ELSE 0 END)-SUM(CASE WHEN it.transaction_type='RETURN' AND it.quantity_delta>0 THEN it.quantity_delta ELSE 0 END),0)$$,$$COALESCE(-SUM(CASE WHEN it.reference_type='SALE' AND it.quantity_delta<0 THEN it.quantity_delta ELSE 0 END),0)$$); EXECUTE def; END $do$;

INSERT INTO schema_migrations(version) VALUES('027_release_convergence') ON CONFLICT(version) DO NOTHING;
