import fs from 'node:fs';
import assert from 'node:assert/strict';

const page = fs.readFileSync(new URL('../app/page.tsx', import.meta.url), 'utf8');
const products = fs.readFileSync(new URL('../app/products/page.tsx', import.meta.url), 'utf8');
const inventory = fs.readFileSync(new URL('../app/inventory/page.tsx', import.meta.url), 'utf8');
const shell = fs.readFileSync(new URL('../components/app-shell.tsx', import.meta.url), 'utf8');
const api = fs.readFileSync(new URL('../lib/api.ts', import.meta.url), 'utf8');
const proxy = fs.readFileSync(new URL('../app/api/lexa/[...path]/route.ts', import.meta.url), 'utf8');

assert.match(api, /fetch\(`\/api\/lexa\$\{path\}`/);
assert.match(page, /Command Centre/);
assert.match(page, /TODAY'S WORK/);
assert.match(page, /NEEDS ATTENTION/);
assert.match(products, /Variants/);
assert.match(products, /Pricing/);
assert.match(products, /Barcodes/);
assert.match(products, /Inventory/);
assert.match(inventory, /Adjustments/);
assert.match(inventory, /Counts/);
assert.match(inventory, /Transfers/);
assert.match(inventory, /Locations/);
assert.match(shell, /Ask LEXA/);
assert.match(shell, /Sales/);
assert.match(shell, /Purchasing/);
assert.match(shell, /Ctrl|Meta|key\.toLowerCase/);
assert.match(shell, /Search your business/);
assert.doesNotMatch(page, /PREVIEW-SKU/);
assert.doesNotMatch(page, /BUILD PREVIEW/);
assert.match(proxy, /LEXA_API_URL \|\| process\.env\.NEXT_PUBLIC_API_URL/);
assert.match(proxy, /DEFAULT_API_ORIGIN/);
assert.match(proxy, /authorization/);
console.log('visible product contract: PASS');

assert.doesNotMatch(page, /LEXA_SCHEMA_NOT_READY|WORKSPACE_DATABASE_FAILURE|WORKSPACE_REGISTRATION_FAILURE|request id|request-id|transactional database/i);
assert.doesNotMatch(page, /Database:|LEXA services online|Connection unavailable|Checking business services/);
assert.doesNotMatch(page, /sessionStorage\.removeItem\("lexa_workspace_id"\)/);
assert.match(api, /function restoreSession/);
assert.match(api, /function logout/);
assert.match(api, /function getBarcodes/);
assert.match(api, /function createBarcode/);
assert.match(api, /function createPriceList/);
assert.match(api, /function createPrice/);
assert.match(api, /function getProductInventory/);
assert.match(api, /Idempotency-Key/);
assert.match(api, /createWarehouse/);
assert.match(api, /createLocation/);
console.log('frontend hardening contract: PASS');
