"use client";
import { useEffect, useState } from "react";
import { getAnalyticsOverview, getAnalyticsProducts, getAnalyticsCustomers, getAnalyticsInventoryHealth, getAnalyticsBranches, refreshAnalytics, type AnalyticsOverview, type AnalyticsProductMetric, type AnalyticsCustomerMetric, type AnalyticsInventoryHealth, type AnalyticsBranchMetric } from "../../lib/api";

function today(){return new Date().toISOString().slice(0,10)}
function monthStart(){const d=new Date();d.setDate(1);return d.toISOString().slice(0,10)}
function money(v:string|number){return new Intl.NumberFormat("en-UG",{style:"currency",currency:"UGX",maximumFractionDigits:0}).format(Number(v))}

export default function ReportsPage(){
 const [from,setFrom]=useState(monthStart()); const [to,setTo]=useState(today()); const [overview,setOverview]=useState<AnalyticsOverview|null>(null); const [products,setProducts]=useState<AnalyticsProductMetric[]>([]); const [customers,setCustomers]=useState<AnalyticsCustomerMetric[]>([]); const [inventory,setInventory]=useState<AnalyticsInventoryHealth[]>([]); const [branches,setBranches]=useState<AnalyticsBranchMetric[]>([]); const [busy,setBusy]=useState(true); const [message,setMessage]=useState("");
 async function load(){setBusy(true);setMessage("");try{const [o,p,c,i,b]=await Promise.all([getAnalyticsOverview(from,to),getAnalyticsProducts(from,to),getAnalyticsCustomers(),getAnalyticsInventoryHealth(),getAnalyticsBranches(from,to)]);setOverview(o);setProducts(p);setCustomers(c);setInventory(i);setBranches(b);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load reports.")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function rebuild(){setMessage("");try{await refreshAnalytics(from,to);await load();setMessage("Analytics refreshed from authoritative transactions.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to refresh analytics.")}}
 return <main className="workspace" style={{maxWidth:1500}}>
  <div className="workspace-header"><div><span className="workspace-breadcrumb">LEXA · BUSINESS INTELLIGENCE</span><h1>Reports & Business Intelligence</h1><p>Deterministic business reporting built from sales, payments, inventory and accounting truth.</p></div><div className="header-actions"><a className="button button-soft" href="/">Back</a><button className="button button-soft" onClick={load} disabled={busy}>Refresh</button></div></div>
  {message&&<div className="inline-message">{message}</div>}
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">REPORTING WINDOW</span><h2>Performance period</h2></div><button className="primary" onClick={rebuild} disabled={busy}>Rebuild analytics</button></div><div className="form-grid"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></section>
  <div className="stat-grid">{[["Net sales",overview?.totals.net_sales],["Collected",overview?.totals.payments_collected],["Credit created",overview?.totals.credit_created],["Net cash movement",overview?.totals.net_cash_movement]].map(([label,val])=><section className="stat-card" key={String(label)}><span>{label}</span><strong>{money(val||0)}</strong><small>{overview?.totals.sale_count||0} completed sales in window</small></section>)}</div>
  <div className="two-column"><section className="workspace-section"><div className="section-head"><div><span className="section-label">DAILY TREND</span><h2>Sales and cash movement</h2></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Net sales</th><th>Collected</th><th>Net cash</th></tr></thead><tbody>{overview?.daily.map(r=><tr key={r.business_date}><td>{r.business_date}</td><td>{money(r.net_sales)}</td><td>{money(r.payments_collected)}</td><td>{money(r.net_cash_movement)}</td></tr>)}</tbody></table></div></section>
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">BRANCHES</span><h2>Branch performance</h2></div></div><div className="table-wrap"><table><thead><tr><th>Branch</th><th>Net sales</th><th>Collected</th></tr></thead><tbody>{branches.map(r=><tr key={`${r.branch_id}-${r.business_date}`}><td><b>{r.branch_name||"Branch"}</b><small>{r.business_date}</small></td><td>{money(r.net_sales)}</td><td>{money(r.payments_collected)}</td></tr>)}</tbody></table></div></section></div>
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">PRODUCT PERFORMANCE</span><h2>Sales, COGS and margin</h2></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Units</th><th>Net sales</th><th>COGS</th><th>Gross margin</th></tr></thead><tbody>{products.map((r,i)=><tr key={`${r.variant_id}-${r.business_date}-${i}`}><td><b>{r.product_name||"Product"}</b><small>{r.variant_name||r.sku||""}</small></td><td>{Number(r.units_sold).toLocaleString()}</td><td>{money(r.net_sales)}</td><td>{money(r.cogs)}</td><td>{money(r.gross_margin)}</td></tr>)}</tbody></table></div></section>
  <div className="two-column"><section className="workspace-section"><div className="section-head"><div><span className="section-label">CUSTOMER PATTERNS</span><h2>Commercial relationships</h2></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Net sales</th><th>Outstanding</th></tr></thead><tbody>{customers.map(r=><tr key={r.customer_party_id}><td>{r.customer_name||"Customer"}<small>Last sale {r.last_sale_date||"—"}</small></td><td>{money(r.net_sales)}</td><td>{money(r.outstanding_balance)}</td></tr>)}</tbody></table></div></section>
  <section className="workspace-section"><div className="section-head"><div><span className="section-label">INVENTORY HEALTH</span><h2>Current stock cover</h2></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Available</th><th>Value</th><th>Days cover</th></tr></thead><tbody>{inventory.map(r=><tr key={`${r.location_id}-${r.variant_id}`}><td><b>{r.product_name||"Product"}</b><small>{r.location_name||"Location"}</small></td><td>{Number(r.available).toLocaleString()}</td><td>{money(r.stock_value)}</td><td>{r.days_cover?Number(r.days_cover).toFixed(1):"No velocity"}</td></tr>)}</tbody></table></div></section></div>
 </main>
}
